# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60cda380cb1d5d54abaaa0a1732797cff48aa3eaee7638b039f557318dc42519be835fc19e5ef18f587cfbf39bc05b84fdd73cffa8b913c894c00b5b58af792d

test:
  secret_key_base: d90031206c0e2604e6bd8dcd95601a8221a28f42e4e8b70c72fc77fe75719347d6e0c4057e39c777e0826f87badda0725902d99b303155e0bd8efb6d490c7d0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
